#!/bin/bash
#
echo -e "Sisesta aja väärtus: \c"
read aeg

if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
echo "tere hommikust"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
echo "Tere päevast"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
echo "tere õhtust"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
then
echo "head ööd"
else
echo "vale sisend"
fi
