#!/bin/bash
#
# Enda saavutused antud aines skript
who | cut -f1 -d" " | cut -f2 -d"." > perenimi
who | cut -f1 -d" " | cut -f1 -d"." > eesnimi
paste -d"." perenimi eesnimi > nimed
cat nimed | sort | uniq
# skripti lõpp
